# -*- coding: utf-8 -*-
"""bankmarketing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZTdOG-VZWtxXkZRG08ExjmR6kKoU9-9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/bank.csv")
df

df.info()

df.describe()

for col in df.select_dtypes(include="object").columns:
  print(col)
  print(df[col].unique())

features_na = [features for features in df.columns if df[features].isnull().sum() > 0]
for feature in features_na:
  print(feature, np.round(df[feature].isnull().mean(), 4), "% missing values")
else:
  print("No missing value found")

df.columns

cat_col = ['job', 'marital', 'education', 'default', 'housing','loan', 'contact', 'month', 'poutcome']

# Distribution of categorical columns
plt.figure(figsize=(15, 10))
for i, col in enumerate(cat_col):
  plt.subplot(3, 3, i + 1)
  sns.countplot(data= df, x = col, hue= col, palette = "Set2", order = df[col].value_counts().index)
  plt.title(f"Distribution of {col}")
  plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# Management, blue-collar, and technician roles dominate the dataset, while housemaid and unknown jobs are rare.
# Most customers are married, followed by single, with divorced being the smallest group.
# Secondary education is most common, tertiary is substantial, and unknown education is minimal.
# Default feature seams to not play imp role as it has value of no at higher ratio to yes which can drop
# Peaks in May and lowest toward the end of the year, especially December.
# Previous campaign outcomes are mostly unknown.

plt.figure(figsize=(15,10))
for i, col in enumerate(cat_col):
  plt.subplot(3, 3, i + 1)
  sns.countplot(data = df, x = col, hue= "deposit", palette="Set2", order= df[col].value_counts().index)
  plt.title(f"{col} by deposit")
  plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# Retired customers has high interest to deposit.
# client who has housing loan seems not to be much intested to deposit.
# In month of March, September, October and December customer show high interest to deposit.
# In month of May records are high but customer interest ratio is very less.

# List of numerical variables
numerical_features = [feature for feature in df.columns if ((df[feature].dtypes != 'O') & (feature not in ["deposit"]))]
print("Number of numerical variables:" , len(numerical_features))

# Visualize the numerical variables
df[numerical_features].head()

cor_mat=df[numerical_features].corr()
fig = plt.figure(figsize=(15,7))
sns.heatmap(cor_mat, annot=True)

# It seems no feature is heavily correlated with other features

df["deposit"].value_counts(normalize=True) * 100

# Dataset seems to be balanced

binary_cols = ['default', 'housing', 'loan', 'deposit']
df[binary_cols] = df[binary_cols].apply(lambda x: x.map({'yes': 1, 'no': 0}))

