# -*- coding: utf-8 -*-
"""Iris - classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttJRQc2jGcG_Kzl9gzqygMQ1qdd6o0gW
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('/content/Iris.csv')
df

df = df.drop(columns = ['Id'])
df.head()

df.tail()

df.info()

df.shape

df.columns

df.describe()

col = [ 'Species']
for i in col:
  print(df[i].value_counts())
  # 50 each so data is not biased

# df['Species'].value_counts()
# df.Species.value_counts(normalize = True)

"""### Data Cleaning

#### 3 steps: Missing values, Dulicate values, Inconsistent values

### Missing values
"""

df.isnull().sum()

"""### Duplicate Values"""

df.duplicated()

df['Species'].describe()

df['Species']
df.Species

df.Species.value_counts().plot(kind="bar")
plt.title("Value counts of the Species")
plt.xlabel("Species")
plt.xticks(rotation = 0)
plt.ylabel("Count")
plt.show()

df['Species'].describe()

sns.pairplot(df, hue = "Species")

"""### Scatterplot"""

sns.scatterplot(x="SepalLengthCm", y="SepalWidthCm", hue="Species", data=df, palette="Dark2", s=80)
plt.title("Relationship between SepalLengthCm and SepalWidthCm")
plt.show()

sns.scatterplot(x="PetalLengthCm", y="PetalWidthCm", hue="Species", data=df, palette="Dark2", s=80)
plt.title("Relationship between PetalLengthCm and PetalWidthCm")
plt.show()

sns.scatterplot(x="SepalLengthCm", y="PetalLengthCm", hue="Species", data=df, palette="Dark2", s=80)
plt.title("Relationship between SepalLengthCm and PetalLengthCm")
plt.show()

sns.scatterplot(x="SepalWidthCm", y="PetalWidthCm", hue="Species", data=df, palette="Dark2", s=80)
plt.title("Relationship between SepalWidthCm and PetalWidthCm")
plt.show()

"""### Corelation Matrix

A Table showing correlation coefficients between variables. Each cell in the table shows the correlation between two variables. The value is in the range of -1 to 1. If two variables have high correlation we can neglect one variable from those two.
"""

# df.corr()

numeric_df = df.select_dtypes(include=['float64', 'int64'])
correlation_matrix = numeric_df.corr()
display(correlation_matrix)

numeric_df = df.select_dtypes(include=['float64', 'int64'])
correlation_matrix = numeric_df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap= 'Pastel1')
plt.title('Correlation Matrix of Iris Dataset')
plt.show()

"""### LabelEncoder

### To convert labels into numerics
"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])
df['Species']

"""### Model Training"""

Y = df['Species']
X = df.drop(columns= [ 'Species'])


from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20)
# test size 20% and training size 80%

print(X.shape,X_train.shape,X_test.shape)     #actual data, trained data, testing data

X_test.head()

"""### Logistic Regression"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression()

model.fit(X_train, Y_train)

y_pred = model.predict(X_test)
score = accuracy_score(Y_test, y_pred)
accuracy = score*100
print(accuracy)

y_pred

model.predict([[]])

Y_test

from sklearn.metrics import confusion_matrix

# PRINT THE CONFUSION MATRIX
print("Confusion Matrix")
cm = confusion_matrix(Y_test, y_pred)
print(cm)

plt.figure(figsize = (6, 4))
sns.heatmap(cm, annot = True, fmt = 'd', cmap = 'Blues', cbar = False, annot_kws = {'size' : 14})
plt.xlabel('Predicted Labels', fontsize = 14)
plt.ylabel('True Labels', fontsize = 14)
plt.title('Confusion Matrix', fontsize = 16)
plt.show()

from sklearn.metrics import classification_report

# Generate classification report
report = classification_report(Y_test, y_pred)
print(report)

"""### Decision Tree Classifier"""

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train, Y_train)

y_pred = clf.predict(X_test)
score = accuracy_score(Y_test, y_pred)
accuracy = score*100
print(accuracy)

from sklearn import tree
tree.plot_tree(clf)

from sklearn.metrics import confusion_matrix
y_pred = clf.predict(X_test)

# PRINT THE CONFUSION MATRIX
print("Confusion Matrix")
cm = confusion_matrix(Y_test, y_pred)
print(cm)

plt.figure(figsize = (6, 4))
sns.heatmap(cm, annot = True, fmt = 'd', cmap = 'Blues', cbar = False, annot_kws = {'size' : 14})
plt.xlabel('Predicted Labels', fontsize = 14)
plt.ylabel('True Labels', fontsize = 14)
plt.title('Confusion Matrix', fontsize = 16)
plt.show()

from sklearn.metrics import classification_report

# Generate classification report
report = classification_report(Y_test, y_pred)
print(report)

#entropy, gini, information gainv

"""### GaussianNB"""

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, Y_train)

y_pred = gnb.predict(X_test)
score = accuracy_score(Y_test, y_pred)
accuracy = score*100
print(accuracy)

from sklearn.metrics import confusion_matrix
y_pred = gnb.predict(X_test)

# PRINT THE CONFUSION MATRIX
print("Confusion Matrix")
cm = confusion_matrix(Y_test, y_pred)
print(cm)

plt.figure(figsize = (6, 4))
sns.heatmap(cm, annot = True, fmt = 'd', cmap = 'Blues', cbar = False, annot_kws = {'size' : 14})
plt.xlabel('Predicted Labels', fontsize = 14)
plt.ylabel('True Labels', fontsize = 14)
plt.title('Confusion Matrix', fontsize = 16)
plt.show()

"""svm suport vector machine
svc support vector classifier
svr support vector regressor

### Support Vector Classifier
"""

from sklearn.svm import SVC
sfc = SVC()
sfc.fit(X_train,Y_train)

y_pred = sfc.predict(X_test)
score = accuracy_score(Y_test, y_pred)
accuracy = score*100
print(accuracy)

from sklearn.metrics import confusion_matrix
y_pred = sfc.predict(X_test)

# PRINT THE CONFUSION MATRIX
print("Confusion Matrix")
cm = confusion_matrix(Y_test, y_pred)
print(cm)

plt.figure(figsize = (6, 4))
sns.heatmap(cm, annot = True, fmt = 'd', cmap = 'Blues', cbar = False, annot_kws = {'size' : 14})
plt.xlabel('Predicted Labels', fontsize = 14)
plt.ylabel('True Labels', fontsize = 14)
plt.title('Confusion Matrix', fontsize = 16)
plt.show()

"""### Random Forest Classifier"""

from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")
classifier.fit(X_train, Y_train)

y_pred = classifier.predict(X_test)
score = accuracy_score(Y_test, y_pred)
accuracy = score*100
print(accuracy)

"""### Confusion Matrics"""

from sklearn.metrics import confusion_matrix
y_pred = clf.predict(X_test)

# PRINT THE CONFUSION MATRIX
print("Confusion Matrix")
cm = confusion_matrix(Y_test, y_pred)
print(cm)

plt.figure(figsize = (6, 4))
sns.heatmap(cm, annot = True, fmt = 'd', cmap = 'Blues', cbar = False, annot_kws = {'size' : 14})
plt.xlabel('Predicted Labels', fontsize = 14)
plt.ylabel('True Labels', fontsize = 14)
plt.title('Confusion Matrix', fontsize = 16)
plt.show()

"""### Classification Report"""

from sklearn.metrics import classification_report

# classification report
report = classification_report(Y_test, y_pred)
print(report)